<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EscuelasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
              "id" => 1,
              "description" => "EP N° 1",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 2,
              "description" => "EP N° 10",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 3,
              "description" => "EP N° 11",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 4,
              "description" => "EP N° 12",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 5,
              "description" => "EP N° 13",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 6,
              "description" => "EP N° 14",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 7,
              "description" => "EP N° 15",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 8,
              "description" => "EP N° 16",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 9,
              "description" => "EP N° 17",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 10,
              "description" => "EP N° 18",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 11,
              "description" => "EP N° 19",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 12,
              "description" => "EP N° 2",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 13,
              "description" => "EP N° 20",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 14,
              "description" => "EP N° 28",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 15,
              "description" => "EP N° 3",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 16,
              "description" => "EP N° 30",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 17,
              "description" => "EP N° 31",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 18,
              "description" => "EP N° 32",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 19,
              "description" => "EP N° 4",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 20,
              "description" => "EP N° 5",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 21,
              "description" => "EP N° 6",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 22,
              "description" => "EP N° 7",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 23,
              "description" => "EP N° 8",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 24,
              "description" => "EP N° 9",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 25,
              "description" => "Escuela Parroquial Maria Auxiliadora",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 26,
              "description" => "Instituto Almafuerte",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 27,
              "description" => "Instituto Educación Integral Munro",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 28,
              "description" => "Instituto Esteban Echeverria",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 29,
              "description" => "Instituto Manuel Dorrego",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 30,
              "description" => "Colegio Maria Reina",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 31,
              "description" => "Colegio Virgen del Carmen",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 32,
              "description" => "Escuela 19",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 33,
              "description" => "Escuela N° 32",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 34,
              "description" => "Escuela N° 23",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 35,
              "description" => "Escuela N° 31",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 36,
              "description" => "Escuela N° 8",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 37,
              "description" => "Escuela Cornelio Saavedra",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 38,
              "description" => "San Ladislao",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 39,
              "description" => "Maria Auxiliadora",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 40,
              "description" => "Virgen del Carmen",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 41,
              "description" => "EMPAS",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 42,
              "description" => "ESB N° 1",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 43,
              "description" => "ESB N° 21",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 44,
              "description" => "ESB N° 3",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 45,
              "description" => "ESB N° 4",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 46,
              "description" => "ESB N° 5",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 47,
              "description" => "ESB N° 6",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 48,
              "description" => "ESB N° 7",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 49,
              "description" => "ESB N° 8",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 50,
              "description" => "ESB N° 10",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 51,
              "description" => "ESB N° 11",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 52,
              "description" => "ESB N° 12",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 53,
              "description" => "ESB N° 13",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 54,
              "description" => "ESB N° 17",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 55,
              "description" => "ESB N° 15",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 56,
              "description" => "ESB N° 18",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 57,
              "description" => "ESB N°21",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 58,
              "description" => "ES N° 3",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 59,
              "description" => "ES N° 4",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 60,
              "description" => "ES N° 5",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 61,
              "description" => "ES N° 6",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 62,
              "description" => "ES N° 7",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 63,
              "description" => "ES N° 8",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 64,
              "description" => "ES N° 10",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 65,
              "description" => "ET N° 1",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 66,
              "description" => "ET N° 2",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 67,
              "description" => "ET N° 3",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 68,
              "description" => "ET N° 4",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 69,
              "description" => "ESB N° 23 (S.M.)",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 70,
              "description" => "ESB N° 44 (S.M.)",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 71,
              "description" => "Escuela de Comercio 15 de 15",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 72,
              "description" => "Bachillerato Popular Ñanderoga",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 73,
              "description" => "Colegio Maria Reina",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 74,
              "description" => "Escuela Parroquial Maria Auxiliadora",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 75,
              "description" => "Instituto Almafuerte",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 76,
              "description" => "Instituto Educación Integral Munro",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 77,
              "description" => "Instituto Esteban Echeverria",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 78,
              "description" => "Instituto Jose Hernandez",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 79,
              "description" => "Instituto Manuel Dorrego",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 80,
              "description" => "Centro de Adultos N° 703/1",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 81,
              "description" => "Centro de Adultos N° 704/1",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 82,
              "description" => "Centro de Adultos N° 706/2",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 83,
              "description" => "Centro de Adultos N° 707/2",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 84,
              "description" => "Centro de Adultos N° 708/1",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 85,
              "description" => "Centro de Adultos N° 709/2",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 86,
              "description" => "Terminalidad Online (Adultos 2000)",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 87,
              "description" => "Terminalidad Semipresencial (Esc. Mariano Moreno)",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 88,
              "description" => "OTROS",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 1,
              "nocturna" => 1,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 89,
              "description" => "EES N° 9",
              "infante" => 0,
              "primaria" => 0,
              "secundaria" => 1,
              "nocturna" => 0,
              "dependencia_id" => null,
              "activo" => 1,
              "created_at" => null,
              "updated_at" => null,
            ],
            [
              "id" => 90,
              "description" => "Escuela Parroquial Maria Auxiliadora",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:41:29.000000Z",
              "updated_at" => "2023-09-22T15:41:29.000000Z",
            ],
            [
              "id" => 91,
              "description" => "EP N°1",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:43:05.000000Z",
              "updated_at" => "2023-09-22T15:43:05.000000Z",
            ],
            [
              "id" => 92,
              "description" => "EP N°10",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:43:30.000000Z",
              "updated_at" => "2023-09-22T15:43:30.000000Z",
            ],
            [
              "id" => 93,
              "description" => "EP N°11",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:44:04.000000Z",
              "updated_at" => "2023-09-22T15:44:04.000000Z",
            ],
            [
              "id" => 94,
              "description" => "EP N°12",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:44:23.000000Z",
              "updated_at" => "2023-09-22T15:44:23.000000Z",
            ],
            [
              "id" => 95,
              "description" => "EP N°13",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:44:38.000000Z",
              "updated_at" => "2023-09-22T15:44:38.000000Z",
            ],
            [
              "id" => 96,
              "description" => "EP N°14",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:44:59.000000Z",
              "updated_at" => "2023-09-22T15:44:59.000000Z",
            ],
            [
              "id" => 97,
              "description" => "EP N°15",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:45:16.000000Z",
              "updated_at" => "2023-09-22T15:45:16.000000Z",
            ],
            [
              "id" => 98,
              "description" => "EP N°16",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:45:39.000000Z",
              "updated_at" => "2023-09-22T15:45:39.000000Z",
            ],
            [
              "id" => 99,
              "description" => "EP N°17",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:45:55.000000Z",
              "updated_at" => "2023-09-22T15:45:55.000000Z",
            ],
            [
              "id" => 100,
              "description" => "EP N°18",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:46:08.000000Z",
              "updated_at" => "2023-09-22T15:46:08.000000Z",
            ],
            [
              "id" => 101,
              "description" => "EP N°19",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:46:30.000000Z",
              "updated_at" => "2023-09-22T15:46:30.000000Z",
            ],
            [
              "id" => 102,
              "description" => "EP N°20",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:46:47.000000Z",
              "updated_at" => "2023-09-22T15:46:47.000000Z",
            ],
            [
              "id" => 103,
              "description" => "EP N°2",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:47:40.000000Z",
              "updated_at" => "2023-09-22T15:47:40.000000Z",
            ],
            [
              "id" => 104,
              "description" => "EP N°28",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:52:05.000000Z",
              "updated_at" => "2023-09-22T15:52:05.000000Z",
            ],
            [
              "id" => 105,
              "description" => "EP N°3",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T15:54:50.000000Z",
              "updated_at" => "2023-09-22T15:54:50.000000Z",
            ],
            [
              "id" => 106,
              "description" => "EP N°30",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:18:57.000000Z",
              "updated_at" => "2023-09-22T16:18:57.000000Z",
            ],
            [
              "id" => 107,
              "description" => "EP N°31",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:19:20.000000Z",
              "updated_at" => "2023-09-22T16:19:20.000000Z",
            ],
            [
              "id" => 108,
              "description" => "EP N°32",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:19:29.000000Z",
              "updated_at" => "2023-09-22T16:19:29.000000Z",
            ],
            [
              "id" => 109,
              "description" => "EP N°4",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:19:40.000000Z",
              "updated_at" => "2023-09-22T16:19:40.000000Z",
            ],
            [
              "id" => 110,
              "description" => "EP N°5",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:19:49.000000Z",
              "updated_at" => "2023-09-22T16:19:49.000000Z",
            ],
            [
              "id" => 111,
              "description" => "EP N°6",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:20:01.000000Z",
              "updated_at" => "2023-09-22T16:20:01.000000Z",
            ],
            [
              "id" => 112,
              "description" => "EP N°7",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:20:21.000000Z",
              "updated_at" => "2023-09-22T16:20:21.000000Z",
            ],
            [
              "id" => 113,
              "description" => "EP N°8",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:20:51.000000Z",
              "updated_at" => "2023-09-22T16:20:51.000000Z",
            ],
            [
              "id" => 114,
              "description" => "EP N°9",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:21:01.000000Z",
              "updated_at" => "2023-09-22T16:21:01.000000Z",
            ],
            [
              "id" => 115,
              "description" => "Instituto Almafuerte",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:21:53.000000Z",
              "updated_at" => "2023-09-22T16:21:53.000000Z",
            ],
            [
              "id" => 116,
              "description" => "Instituto Educación Integral Munro",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:22:29.000000Z",
              "updated_at" => "2023-09-22T16:22:29.000000Z",
            ],
            [
              "id" => 117,
              "description" => "Instituto Esteban Echeverria",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:24:17.000000Z",
              "updated_at" => "2023-09-22T16:24:17.000000Z",
            ],
            [
              "id" => 118,
              "description" => "Instituto Manuel Dorrego",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:24:40.000000Z",
              "updated_at" => "2023-09-22T16:24:40.000000Z",
            ],
            [
              "id" => 119,
              "description" => "Colegio Maria Reina",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:25:03.000000Z",
              "updated_at" => "2023-09-22T16:25:03.000000Z",
            ],
            [
              "id" => 120,
              "description" => "Colegio Virgen del Carmen",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:25:32.000000Z",
              "updated_at" => "2023-09-22T16:25:32.000000Z",
            ],
            [
              "id" => 121,
              "description" => "Escuela 19",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:25:47.000000Z",
              "updated_at" => "2023-09-22T16:25:47.000000Z",
            ],
            [
              "id" => 122,
              "description" => "Escuela N°32",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:26:06.000000Z",
              "updated_at" => "2023-09-22T16:26:06.000000Z",
            ],
            [
              "id" => 123,
              "description" => "Escuela N°23",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:26:22.000000Z",
              "updated_at" => "2023-09-22T16:26:22.000000Z",
            ],
            [
              "id" => 124,
              "description" => "Escuela N°31",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:26:41.000000Z",
              "updated_at" => "2023-09-22T16:26:41.000000Z",
            ],
            [
              "id" => 125,
              "description" => "Escuela N°8",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:27:00.000000Z",
              "updated_at" => "2023-09-22T16:27:00.000000Z",
            ],
            [
              "id" => 126,
              "description" => "Escuela Cornelio Saavedra",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:27:22.000000Z",
              "updated_at" => "2023-09-22T16:27:22.000000Z",
            ],
            [
              "id" => 127,
              "description" => "San Ladislao",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:27:38.000000Z",
              "updated_at" => "2023-09-22T16:27:38.000000Z",
            ],
            [
              "id" => 128,
              "description" => "Maria Auxiliadora",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:27:59.000000Z",
              "updated_at" => "2023-09-22T16:27:59.000000Z",
            ],
            [
              "id" => 129,
              "description" => "Otros",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 1,
              "nocturna" => 1,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:28:16.000000Z",
              "updated_at" => "2023-09-22T16:28:16.000000Z",
            ],
            [
              "id" => 130,
              "description" => "Virgen Del Carmen",
              "infante" => 0,
              "primaria" => 1,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-22T16:28:42.000000Z",
              "updated_at" => "2023-09-22T16:28:42.000000Z",
            ],
            [
              "id" => 131,
              "description" => "NENI",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T01:48:46.000000Z",
              "updated_at" => "2023-09-26T01:48:46.000000Z",
            ],
            [
              "id" => 132,
              "description" => "Jardin de Infantes Comun Nro 01 de 15",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:10:14.000000Z",
              "updated_at" => "2023-09-26T13:10:14.000000Z",
            ],
            [
              "id" => 133,
              "description" => "Jardin de Infantes Nro. 3",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:13:08.000000Z",
              "updated_at" => "2023-09-26T13:13:08.000000Z",
            ],
            [
              "id" => 134,
              "description" => "Jardin de Infantes Nro. 4",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:13:44.000000Z",
              "updated_at" => "2023-09-26T13:13:44.000000Z",
            ],
            [
              "id" => 135,
              "description" => "Jardin de Infantes Nro. 5",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:14:06.000000Z",
              "updated_at" => "2023-09-26T13:14:06.000000Z",
            ],
            [
              "id" => 136,
              "description" => "Jardin de Infantes Nro. 6",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:14:25.000000Z",
              "updated_at" => "2023-09-26T13:14:25.000000Z",
            ],
            [
              "id" => 137,
              "description" => "Jardin de Infantes Nro. 8",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:15:40.000000Z",
              "updated_at" => "2023-09-26T13:15:40.000000Z",
            ],
            [
              "id" => 138,
              "description" => "Jardin de Infantes Nro. 9",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:31:19.000000Z",
              "updated_at" => "2023-09-26T13:31:19.000000Z",
            ],
            [
              "id" => 139,
              "description" => "Jardin de Infantes Nro. 10",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:31:59.000000Z",
              "updated_at" => "2023-09-26T13:31:59.000000Z",
            ],
            [
              "id" => 140,
              "description" => "Jardin de Infantes Nro. 901",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:32:26.000000Z",
              "updated_at" => "2023-09-26T13:32:26.000000Z",
            ],
            [
              "id" => 141,
              "description" => "Jardin de Infantes Nro. 904",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:32:47.000000Z",
              "updated_at" => "2023-09-26T13:32:47.000000Z",
            ],
            [
              "id" => 142,
              "description" => "Jardin de Infantes Los Horneros Nro. 906",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:33:16.000000Z",
              "updated_at" => "2023-09-26T13:33:16.000000Z",
            ],
            [
              "id" => 143,
              "description" => "Jardin de Infantes Nro. 908",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:36:53.000000Z",
              "updated_at" => "2023-09-26T13:36:53.000000Z",
            ],
            [
              "id" => 144,
              "description" => "Jardin de Infantes Nro. 912",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:42:44.000000Z",
              "updated_at" => "2023-09-26T13:42:44.000000Z",
            ],
            [
              "id" => 145,
              "description" => "Jardin de Infantes Nro. 913",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:43:21.000000Z",
              "updated_at" => "2023-09-26T13:43:21.000000Z",
            ],
            [
              "id" => 146,
              "description" => "Jardin de Infantes Nro. 914",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:43:41.000000Z",
              "updated_at" => "2023-09-26T13:43:41.000000Z",
            ],
            [
              "id" => 147,
              "description" => "Jardin de Infantes Nro. 917",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T13:44:02.000000Z",
              "updated_at" => "2023-09-26T13:44:02.000000Z",
            ],
            [
              "id" => 148,
              "description" => "Jardin de Infantes Nro. 918",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:47:18.000000Z",
              "updated_at" => "2023-09-26T14:47:18.000000Z",
            ],
            [
              "id" => 149,
              "description" => "Jardin de Infantes Nro. 934",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:47:38.000000Z",
              "updated_at" => "2023-09-26T14:47:38.000000Z",
            ],
            [
              "id" => 150,
              "description" => "Jardin de Infantes Nro. 945 Lola Mora",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:48:16.000000Z",
              "updated_at" => "2023-09-26T14:48:16.000000Z",
            ],
            [
              "id" => 151,
              "description" => "Instituto Italiano",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:48:38.000000Z",
              "updated_at" => "2023-09-26T14:48:38.000000Z",
            ],
            [
              "id" => 152,
              "description" => "Jardin San Pablo de la Cruz",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:49:11.000000Z",
              "updated_at" => "2023-09-26T14:49:11.000000Z",
            ],
            [
              "id" => 153,
              "description" => "Jardin Virgen del Carmen",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:50:44.000000Z",
              "updated_at" => "2023-09-26T14:50:44.000000Z",
            ],
            [
              "id" => 154,
              "description" => "Chispita",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:51:01.000000Z",
              "updated_at" => "2023-09-26T14:51:01.000000Z",
            ],
            [
              "id" => 155,
              "description" => "Conejin",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:51:15.000000Z",
              "updated_at" => "2023-09-26T14:51:15.000000Z",
            ],
            [
              "id" => 156,
              "description" => "Jardin de Infantes 19 de 15",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:51:38.000000Z",
              "updated_at" => "2023-09-26T14:51:38.000000Z",
            ],
            [
              "id" => 157,
              "description" => "Jardin de Infantes Ameghino",
              "infante" => 1,
              "primaria" => 0,
              "secundaria" => 0,
              "nocturna" => 0,
              "dependencia_id" => 12,
              "activo" => 1,
              "created_at" => "2023-09-26T14:54:50.000000Z",
              "updated_at" => "2023-09-26T14:54:50.000000Z",
            ],
        ];

        DB::table('escuelas')->insert($data);
    }
}
