<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipoTramiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [1, 1, 'INSCRIPCIÓN A ACTIVIDADES', 1],
            [2, 1, 'INSCRIPCIÓN A COMEDORES', 1],
            [3, 1, 'ASESORAMIENTO', 1],
            [4, 2, 'ENTREVISTA PROFESIONAL CON TURNO', 1],
            [5, 2, 'MULETAS', 1],
            [6, 2, 'LENTES', 1],
            [7, 2, 'RETIRA PASE', 1],
            [8, 2, 'PLANTILLAS', 1],
            [9, 2, 'PRÓTESIS', 1],
            [12, 2, 'PASE DE TRANSPORTE', 1],
            [13, 2, 'SILLA DE RUEDAS', 1],
            [14, 2, 'ASISTENCIA ALIMENTARIA', 1],
            [77, 10, 'ASISTENCIA ALIMENTARIA COVID-19', 1],
            [78, 10, 'TARJETA ALIMENTAR', 1],
            [15, 3, 'CONSTITUCIÓN DE ASOCIACIONES CIVILES (PERSONERÍA JURÍDICA)', 1],
            [16, 3, 'PEDIDOS PARA EVENTOS', 1],
            [17, 3, 'INSCRIPCIÓN MUNICIPAL DE ENTIDADES DE BIEN PÚBLICO', 1],
            [18, 3, 'PROGRAMA TARIFA SOCIAL (ERAS)', 1],
            [19, 3, 'RÚBRICA DE LIBROS', 1],
            [20, 3, 'VISTA DE BALANCES', 1],
            [21, 3, 'CERTIFICADOS DE VIGENCIA', 1],
            [22, 3, 'CAPACITACIÓN', 1],
            [23, 3, 'ASESORAMIENTO GENERAL', 1],
            [24, 3, 'SUBSIDIOS', 1],
            [25, 5, 'PLAN MÁS VIDA', 1],
            [26, 5, 'CELIAQUÍA', 1],
            [27, 5, 'BOLSÓN DE ALIMENTOS', 1],
            [28, 5, 'SUBSIDIO SUBSISTENCIA', 1],
            [29, 5, 'SUBSIDIO MICROEMPRENDIMIENTO', 1],
            [30, 5, 'SILLA DE RUEDAS', 1],
            [31, 5, 'MULETAS/BASTÓN/TRÍPODE', 1],
            [32, 5, 'PLANTILLAS', 1],
            [33, 5, 'LENTES', 1],
            [34, 5, 'COLCHÓN', 1],
            [35, 5, 'CAMA', 1],
            [36, 5, 'FRAZADA', 1],
            [39, 5, 'SANEAMIENTO', 1],
            [40, 5, 'CUADRILLA GESTIÓN TERRITORIAL', 1],
            [41, 5, 'DESTAPE DE POZOS', 1],
            [42, 5, 'RECLAMOS CLOACAS / RED DE AGUA', 1],
            [43, 5, 'RECLAMOS ELÉCTRICOS', 1],
            [44, 5, 'SEPELIOS', 1],
            [45, 5, 'CONSULTA', 1],
            [46, 5, 'TICKET ALIMENTARIO', 1],
            [47, 5, 'OTROS', 1],
            [48, 6, 'CONSTITUCIÓN DE ASOCIACIONES CIVILES (PERSONERÍA JURÍDICA)', 1],
            [49, 6, 'INSCRIPCIÓN A CURSOS Y TALLERES', 1],
            [50, 6, 'ENTREVISTA CON PROFESIONAL PARA DERIVACIÓN A TRATAMIENTO', 1],
            [51, 6, 'INSCRIPCIÓN A TRATAMIENTO GRUPAL DE HOMBRES CON CONDUCTAS VIOLENTAS', 1],
            [52, 6, 'ASESORAMIENTO LEGAL EN TEMAS DE GÉNERO', 1],
            [53, 6, 'ASESORAMIENTO LEGAL EN TEMAS DE DIVERSIDAD SEXUAL', 1],
            [54, 6, 'INSCRIPCIÓN PROGRAMA DE EMPRENDIMIENTOS', 1],
            [55, 6, 'ENTREVISTA POR BOTÓN ANTIPÁNICO', 1],
            [56, 6, 'ADMISIÓN POR LICENCIA ESPECIAL (EMPLEADOS MUNICIPALES)', 1],
            [57, 7, 'MATERIALES DE CONSTRUCCIÓN', 1],
            [58, 7, 'ESTADO DE SOLICITUD DE ESCRITURA', 1],
            [59, 7, 'SOLICITUD DE VIVIENDA', 1],
            [60, 7, 'SOLICITUD DE RELOCALIZACIÓN', 1],
            [61, 7, 'SOLICITUD DE SUBSIDIO', 1],
            [62, 7, 'RECLAMOS EN COMPLEJOS HABITACIONALES', 1],
            [63, 7, 'RECLAMOS ELÉCTRICOS', 1],
            [64, 7, 'RECLAMOS CLOACAS / RED DE AGUA', 1],
            [65, 7, 'SOLICITUD MEJORAMIENTO AMBIENTAL', 1],
            [66, 8, 'ASISTENCIA TÉCNICO - PROFESIONAL', 1],
            [67, 8, 'SERVICIO LOCAL', 1],
            [68, 8, 'ATENCIÓN EN GUARDIA', 1],
            [69, 8, 'ASESORAMIENTO LEGAL', 1],
            [70, 9, 'ATENCIÓN A ADULTOS MAYORES EN SITUACIÓN DE VULNERABILIDAD', 1],
            [71, 9, 'ATENCIÓN A PERSONAS EN SITUACIÓN DE CALLE', 1],
            [72, 9, 'EXIMICIÓN DE TASAS, DOCUMENTOS Y OTROS', 1],
            [73, 9, 'SOLICITUD DE INTERVENCIONES POR ACUMULADORES - CASAS TOMADAS - PREDIOS INTRUSADOS - VULNERACIÓN DE DERECHOS', 1],
            [74, 9, 'INTERVENCIONES SOLICITADAS POR IPS U OTRAS INSTITUCIONES', 1],
            [75, 9, 'BONOS JUBILADOS', 1],
            [76, 9, 'PROBATION', 1],
            [86, 2, 'INCLUSION EDUCATIVA', 1],
            [87, 2, 'INCLUSION LABORAL', 1],
            [88, 2, 'INCLUSION RECREATIVA', 1],
            [89, 2, 'VIDA INDEPENDIENTE', 1],
            [90, 2, 'SOCIO AMBIENTAL', 1],
            [91, 2, 'AUDIFONOS', 1],
            [92, 2, 'CAMA - COLCHONES - FRAZADAS', 1],
            [93, 2, 'BASTON', 1],
            [94, 2, 'OTROS ELEMENTOS', 1],
            [10, 2, 'ASESORAMIENTO GENERAL', 1],
            [11, 2, 'ORIENTACIÓN', 0],
            [37, 5, 'INSCRIPCIÓN A COMEDOR', 0],
            [38, 5, 'INSCRIPCIÓN A COMEDOR POR TERCERA EDAD', 0],
            [99, 11, 'INTERVENCIONES EN AISLAMIENTOS TERMICOS EN PAREDES EXTERIORES', 1],
            [95, 5, 'ASISTENCIA A COMEDOR PERSONAS CON DISCAPACIDAD', 1],
            [96, 5, 'ASISTENCIA A COMEDOR JOVENES', 1],
            [83, 5, 'ASISTENCIA A COMEDOR NIÑAS/NIÑOS', 1],
            [84, 5, 'ENTREVISTA CON TRABAJADORA/TRABAJADOS SOCIAL', 1],
            [79, 12, 'INFANCIA', 1],
            [81, 5, 'ASISTENCIA A COMEDOR', 0],
            [80, 13, 'JUVENTUD', 1],
            [82, 5, 'ASISTENCIA A COMEDOR PERSONAS MAYORES', 1],
            [85, 7, 'ATENCION CON PROFESIONAL', 1],
            [97, 11, 'INTERVENCIONES SANITARIAS', 1],
            [98, 11, 'INTERVENCIONES EN AISLAMIENTOS TERMICOS EN TECHOS', 1],
            [100, 13, 'IGUALDAD DE GÉNERO', 1],
            [101, 14, 'ASISTENCIA ALIMENTARIA', 1],
            [102, 14, 'ASISTENCIA ALIMENTARIA', 1],
            [103, 14, 'BONOS', 1],
            [104, 14, 'CAMA - COLCHONES - FRAZADAS', 1],
            [105, 14, 'ENTREVISTA PROFESIONAL CON TURNO', 1],
            [106, 14, 'EXIMICIÓN DE TASAS, DOCUMENTOS, OTROS', 1],
            [107, 14, 'INTERVENCIONES SOLICITADAS POR IPS U OTRAS INSTITUCIONES', 1],
            [108, 14, 'LENTES', 1],
            [109, 14, 'SOCIOAMBIENTAL', 1],
            [110, 14, 'SOLICITUD DE INTERVENCIONES POR ACUMULADORES - CASAS TOMADAS - PREDIOS INTRUSADOS', 1],
            [111, 14, 'RECREATIVO', 1],
        ];

        foreach ($data as $row) {
            DB::table('tipo_tramite')->insert([
                'id' => $row[0],
                'dependencia_id' => $row[1],
                'description' => $row[2],
                'activo' => $row[3],
            ]);
        }
    }
}
