<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipoTramiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =  [
            [
              "id" => 1,
              "dependencia_id" => 1,
              "description" => "INSCRIPCIÓN A ACTIVIDADES",
              "activo" => 1,
            ],
            [
              "id" => 2,
              "dependencia_id" => 1,
              "description" => "INSCRIPCIÓN A COMEDORES",
              "activo" => 1,
            ],
            [
              "id" => 3,
              "dependencia_id" => 1,
              "description" => "ASESORAMIENTO",
              "activo" => 1,
            ],
            [
              "id" => 4,
              "dependencia_id" => 2,
              "description" => "ENTREVISTA PROFESIONAL CON TURNO",
              "activo" => 1,
            ],
            [
              "id" => 5,
              "dependencia_id" => 2,
              "description" => "MULETAS",
              "activo" => 0,
            ],
            [
              "id" => 6,
              "dependencia_id" => 2,
              "description" => "LENTES",
              "activo" => 1,
            ],
            [
              "id" => 7,
              "dependencia_id" => 2,
              "description" => "RETIRA PASE",
              "activo" => 1,
            ],
            [
              "id" => 8,
              "dependencia_id" => 2,
              "description" => "PLANTILLAS",
              "activo" => 1,
            ],
            [
              "id" => 9,
              "dependencia_id" => 2,
              "description" => "PRÓTESIS",
              "activo" => 1,
            ],
            [
              "id" => 10,
              "dependencia_id" => 2,
              "description" => "ASESORAMIENTO GENERAL",
              "activo" => 1,
            ],
            [
              "id" => 11,
              "dependencia_id" => 2,
              "description" => "ORIENTACIÓN",
              "activo" => 0,
            ],
            [
              "id" => 12,
              "dependencia_id" => 2,
              "description" => "PASE DE TRANSPORTE",
              "activo" => 1,
            ],
            [
              "id" => 13,
              "dependencia_id" => 2,
              "description" => "SILLA DE RUEDAS",
              "activo" => 1,
            ],
            [
              "id" => 14,
              "dependencia_id" => 2,
              "description" => "ASISTENCIA ALIMENTARIA",
              "activo" => 1,
            ],
            [
              "id" => 15,
              "dependencia_id" => 3,
              "description" => "CONSTITUCIÓN DE ASOCIACIONES CIVILES (PERSONERÍA JURÍDICA)",
              "activo" => 1,
            ],
            [
              "id" => 16,
              "dependencia_id" => 3,
              "description" => "PEDIDOS PARA EVENTOS",
              "activo" => 1,
            ],
            [
              "id" => 17,
              "dependencia_id" => 3,
              "description" => "INSCRIPCIÓN MUNICIPAL DE ENTIDADES DE BIEN PÚBLICO",
              "activo" => 1,
            ],
            [
              "id" => 18,
              "dependencia_id" => 3,
              "description" => "PROGRAMA TARIFA SOCIAL (ERAS)",
              "activo" => 1,
            ],
            [
              "id" => 19,
              "dependencia_id" => 3,
              "description" => "RÚBRICA DE LIBROS",
              "activo" => 1,
            ],
            [
              "id" => 20,
              "dependencia_id" => 3,
              "description" => "VISTA DE BALANCES",
              "activo" => 1,
            ],
            [
              "id" => 21,
              "dependencia_id" => 3,
              "description" => "CERTIFICADOS DE VIGENCIA",
              "activo" => 1,
            ],
            [
              "id" => 22,
              "dependencia_id" => 3,
              "description" => "CAPACITACIÓN",
              "activo" => 1,
            ],
            [
              "id" => 23,
              "dependencia_id" => 3,
              "description" => "ASESORAMIENTO GENERAL",
              "activo" => 1,
            ],
            [
              "id" => 24,
              "dependencia_id" => 3,
              "description" => "SUBSIDIOS",
              "activo" => 1,
            ],
            [
              "id" => 25,
              "dependencia_id" => 5,
              "description" => "PLAN MÁS VIDA",
              "activo" => 1,
            ],
            [
              "id" => 26,
              "dependencia_id" => 5,
              "description" => "CELIAQUÍA",
              "activo" => 1,
            ],
            [
              "id" => 27,
              "dependencia_id" => 5,
              "description" => "BOLSÓN DE ALIMENTOS",
              "activo" => 1,
            ],
            [
              "id" => 28,
              "dependencia_id" => 5,
              "description" => "SUBSIDIO SUBSISTENCIA",
              "activo" => 1,
            ],
            [
              "id" => 29,
              "dependencia_id" => 5,
              "description" => "SUBSIDIO MICROEMPRENDIMIENTO",
              "activo" => 1,
            ],
            [
              "id" => 30,
              "dependencia_id" => 5,
              "description" => "SILLA DE RUEDAS",
              "activo" => 1,
            ],
            [
              "id" => 31,
              "dependencia_id" => 5,
              "description" => "MULETAS/BASTÓN/TRÍPODE",
              "activo" => 1,
            ],
            [
              "id" => 32,
              "dependencia_id" => 5,
              "description" => "PLANTILLAS",
              "activo" => 1,
            ],
            [
              "id" => 33,
              "dependencia_id" => 5,
              "description" => "LENTES",
              "activo" => 1,
            ],
            [
              "id" => 34,
              "dependencia_id" => 5,
              "description" => "COLCHÓN",
              "activo" => 1,
            ],
            [
              "id" => 35,
              "dependencia_id" => 5,
              "description" => "CAMA",
              "activo" => 1,
            ],
            [
              "id" => 36,
              "dependencia_id" => 5,
              "description" => "FRAZADA",
              "activo" => 1,
            ],
            [
              "id" => 37,
              "dependencia_id" => 5,
              "description" => "INSCRIPCIÓN A COMEDOR",
              "activo" => 0,
            ],
            [
              "id" => 38,
              "dependencia_id" => 5,
              "description" => "INSCRIPCIÓN A COMEDOR POR TERCERA EDAD",
              "activo" => 0,
            ],
            [
              "id" => 39,
              "dependencia_id" => 5,
              "description" => "SANEAMIENTO",
              "activo" => 1,
            ],
            [
              "id" => 40,
              "dependencia_id" => 5,
              "description" => "CUADRILLA GESTIÓN TERRITORIAL",
              "activo" => 1,
            ],
            [
              "id" => 41,
              "dependencia_id" => 5,
              "description" => "DESTAPE DE POZOS",
              "activo" => 1,
            ],
            [
              "id" => 42,
              "dependencia_id" => 5,
              "description" => "RECLAMOS CLOACAS / RED DE AGUA",
              "activo" => 1,
            ],
            [
              "id" => 43,
              "dependencia_id" => 5,
              "description" => "RECLAMOS ELÉCTRICOS",
              "activo" => 1,
            ],
            [
              "id" => 44,
              "dependencia_id" => 5,
              "description" => "SEPELIOS",
              "activo" => 1,
            ],
            [
              "id" => 45,
              "dependencia_id" => 5,
              "description" => "CONSULTA",
              "activo" => 1,
            ],
            [
              "id" => 46,
              "dependencia_id" => 5,
              "description" => "TICKET ALIMENTARIO",
              "activo" => 1,
            ],
            [
              "id" => 47,
              "dependencia_id" => 5,
              "description" => "OTROS",
              "activo" => 1,
            ],
            [
              "id" => 48,
              "dependencia_id" => 6,
              "description" => "ADMISION",
              "activo" => 0,
            ],
            [
              "id" => 49,
              "dependencia_id" => 6,
              "description" => "INSCRIPCIÓN A CURSOS Y TALLERES",
              "activo" => 1,
            ],
            [
              "id" => 50,
              "dependencia_id" => 6,
              "description" => "ENTREVISTA",
              "activo" => 0,
            ],
            [
              "id" => 51,
              "dependencia_id" => 6,
              "description" => "RESPUESTA A DERIVACION",
              "activo" => 1,
            ],
            [
              "id" => 52,
              "dependencia_id" => 6,
              "description" => "ASESORAMIENTO LEGAL",
              "activo" => 1,
            ],
            [
              "id" => 53,
              "dependencia_id" => 6,
              "description" => "ASESORAMIENTO LEGAL EN TEMAS DE DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 54,
              "dependencia_id" => 6,
              "description" => "INSCRIPCIÓN PROGRAMA DE EMPRENDIMIENTOS",
              "activo" => 1,
            ],
            [
              "id" => 55,
              "dependencia_id" => 6,
              "description" => "BOTÓN ANTIPÁNICO",
              "activo" => 1,
            ],
            [
              "id" => 56,
              "dependencia_id" => 6,
              "description" => "LICENCIA ESPECIAL",
              "activo" => 1,
            ],
            [
              "id" => 57,
              "dependencia_id" => 7,
              "description" => "MATERIALES DE CONSTRUCCIÓN",
              "activo" => 1,
            ],
            [
              "id" => 58,
              "dependencia_id" => 7,
              "description" => "ESTADO DE SOLICITUD DE ESCRITURA",
              "activo" => 1,
            ],
            [
              "id" => 59,
              "dependencia_id" => 7,
              "description" => "SOLICITUD DE VIVIENDA",
              "activo" => 1,
            ],
            [
              "id" => 60,
              "dependencia_id" => 7,
              "description" => "SOLICITUD DE RELOCALIZACIÓN",
              "activo" => 1,
            ],
            [
              "id" => 61,
              "dependencia_id" => 7,
              "description" => "SOLICITUD DE SUBSIDIO",
              "activo" => 1,
            ],
            [
              "id" => 62,
              "dependencia_id" => 7,
              "description" => "RECLAMOS EN COMPLEJOS HABITACIONALES",
              "activo" => 1,
            ],
            [
              "id" => 63,
              "dependencia_id" => 7,
              "description" => "RECLAMOS ELÉCTRICOS",
              "activo" => 1,
            ],
            [
              "id" => 64,
              "dependencia_id" => 7,
              "description" => "RECLAMOS CLOACAS / RED DE AGUA",
              "activo" => 1,
            ],
            [
              "id" => 65,
              "dependencia_id" => 7,
              "description" => "SOLICITUD MEJORAMIENTO AMBIENTAL",
              "activo" => 1,
            ],
            [
              "id" => 66,
              "dependencia_id" => 8,
              "description" => "ASISTENCIA TÉCNICO - PROFESIONAL",
              "activo" => 1,
            ],
            [
              "id" => 67,
              "dependencia_id" => 8,
              "description" => "SERVICIO LOCAL",
              "activo" => 1,
            ],
            [
              "id" => 68,
              "dependencia_id" => 8,
              "description" => "ATENCIÓN EN GUARDIA",
              "activo" => 1,
            ],
            [
              "id" => 69,
              "dependencia_id" => 8,
              "description" => "ASESORAMIENTO LEGAL",
              "activo" => 1,
            ],
            [
              "id" => 70,
              "dependencia_id" => 9,
              "description" => "ATENCIÓN A ADULTOS MAYORES EN SITUACIÓN DE VULNERABILIDAD",
              "activo" => 1,
            ],
            [
              "id" => 71,
              "dependencia_id" => 9,
              "description" => "ATENCIÓN A PERSONAS EN SITUACIÓN DE CALLE",
              "activo" => 1,
            ],
            [
              "id" => 72,
              "dependencia_id" => 9,
              "description" => "EXIMICIÓN DE TASAS, DOCUMENTOS Y OTROS",
              "activo" => 1,
            ],
            [
              "id" => 73,
              "dependencia_id" => 9,
              "description" => "SOLICITUD DE INTERVENCIONES POR ACUMULADORES - CASAS TOMADAS - PREDIOS INTRUSADOS - VULNERACIÓN DE D",
              "activo" => 1,
            ],
            [
              "id" => 74,
              "dependencia_id" => 9,
              "description" => "INTERVENCIONES SOLICITADAS POR IPS U OTRAS INSTITUCIONES",
              "activo" => 1,
            ],
            [
              "id" => 75,
              "dependencia_id" => 9,
              "description" => "BONOS JUBILADOS",
              "activo" => 1,
            ],
            [
              "id" => 76,
              "dependencia_id" => 9,
              "description" => "PROBATION",
              "activo" => 1,
            ],
            [
              "id" => 77,
              "dependencia_id" => 10,
              "description" => "ASISTENCIA ALIMENTARIA COVID-19",
              "activo" => 1,
            ],
            [
              "id" => 78,
              "dependencia_id" => 10,
              "description" => "TARJETA ALIMENTAR",
              "activo" => 1,
            ],
            [
              "id" => 79,
              "dependencia_id" => 12,
              "description" => "INFANCIA",
              "activo" => 1,
            ],
            [
              "id" => 80,
              "dependencia_id" => 13,
              "description" => "JUVENTUD",
              "activo" => 1,
            ],
            [
              "id" => 81,
              "dependencia_id" => 5,
              "description" => "ASISTENCIA A COMEDOR",
              "activo" => 0,
            ],
            [
              "id" => 82,
              "dependencia_id" => 5,
              "description" => "ASISTENCIA A COMEDOR PERSONAS MAYORES",
              "activo" => 1,
            ],
            [
              "id" => 83,
              "dependencia_id" => 5,
              "description" => "ASISTENCIA A COMEDOR NIÑAS/NIÑOS",
              "activo" => 1,
            ],
            [
              "id" => 84,
              "dependencia_id" => 5,
              "description" => "ENTREVISTA CON TRABAJADORA/TRABAJADOS SOCIAL",
              "activo" => 1,
            ],
            [
              "id" => 85,
              "dependencia_id" => 7,
              "description" => "ATENCION CON PROFESIONAL",
              "activo" => 1,
            ],
            [
              "id" => 86,
              "dependencia_id" => 2,
              "description" => "INCLUSION EDUCATIVA",
              "activo" => 1,
            ],
            [
              "id" => 87,
              "dependencia_id" => 2,
              "description" => "INCLUSION LABORAL",
              "activo" => 1,
            ],
            [
              "id" => 88,
              "dependencia_id" => 2,
              "description" => "INCLUSION RECREATIVA",
              "activo" => 1,
            ],
            [
              "id" => 89,
              "dependencia_id" => 2,
              "description" => "VIDA INDEPENDIENTE",
              "activo" => 1,
            ],
            [
              "id" => 90,
              "dependencia_id" => 2,
              "description" => "SOCIO AMBIENTAL",
              "activo" => 1,
            ],
            [
              "id" => 91,
              "dependencia_id" => 2,
              "description" => "AUDIFONOS",
              "activo" => 1,
            ],
            [
              "id" => 92,
              "dependencia_id" => 2,
              "description" => "CAMA - COLCHONES - FRAZADAS",
              "activo" => 1,
            ],
            [
              "id" => 93,
              "dependencia_id" => 2,
              "description" => "BASTON",
              "activo" => 1,
            ],
            [
              "id" => 94,
              "dependencia_id" => 2,
              "description" => "OTROS ELEMENTOS",
              "activo" => 1,
            ],
            [
              "id" => 95,
              "dependencia_id" => 5,
              "description" => "ASISTENCIA A COMEDOR PERSONAS CON DISCAPACIDAD",
              "activo" => 1,
            ],
            [
              "id" => 96,
              "dependencia_id" => 5,
              "description" => "ASISTENCIA A COMEDOR JOVENES",
              "activo" => 1,
            ],
            [
              "id" => 97,
              "dependencia_id" => 11,
              "description" => "INTERVENCIONES SANITARIAS",
              "activo" => 1,
            ],
            [
              "id" => 98,
              "dependencia_id" => 11,
              "description" => "INTERVENCIONES EN AISLAMIENTOS TERMICOS EN TECHOS",
              "activo" => 1,
            ],
            [
              "id" => 99,
              "dependencia_id" => 11,
              "description" => "INTERVENCIONES EN AISLAMIENTOS TERMICOS EN PAREDES EXTERIORES",
              "activo" => 1,
            ],
            [
              "id" => 100,
              "dependencia_id" => 13,
              "description" => "IGUALDAD DE GÉNERO",
              "activo" => 0,
            ],
            [
              "id" => 101,
              "dependencia_id" => 14,
              "description" => "ASISTENCIA ALIMENTARIA",
              "activo" => 0,
            ],
            [
              "id" => 102,
              "dependencia_id" => 14,
              "description" => "ASISTENCIA ALIMENTARIA",
              "activo" => 1,
            ],
            [
              "id" => 103,
              "dependencia_id" => 14,
              "description" => "BONOS",
              "activo" => 1,
            ],
            [
              "id" => 104,
              "dependencia_id" => 14,
              "description" => "CAMA - COLCHONES - FRAZADAS",
              "activo" => 1,
            ],
            [
              "id" => 105,
              "dependencia_id" => 14,
              "description" => "ENTREVISTA PROFESIONAL CON TURNO",
              "activo" => 1,
            ],
            [
              "id" => 106,
              "dependencia_id" => 14,
              "description" => "EXIMICIÓN DE TASAS, DOCUMENTOS, OTROS",
              "activo" => 1,
            ],
            [
              "id" => 107,
              "dependencia_id" => 14,
              "description" => "INTERVENCIONES SOLICITADAS POR IPS U OTRAS INSTITUCIONES",
              "activo" => 1,
            ],
            [
              "id" => 108,
              "dependencia_id" => 14,
              "description" => "LENTES",
              "activo" => 1,
            ],
            [
              "id" => 109,
              "dependencia_id" => 14,
              "description" => "SOCIOAMBIENTAL",
              "activo" => 1,
            ],
            [
              "id" => 110,
              "dependencia_id" => 14,
              "description" => "SOLICITUD DE INTERVENCIONES POR ACUMULADORES - CASAS TOMADAS - PREDIOS INTRUSADOS",
              "activo" => 1,
            ],
            [
              "id" => 111,
              "dependencia_id" => 14,
              "description" => "RECREATIVO",
              "activo" => 1,
            ],
            [
              "id" => 112,
              "dependencia_id" => 2,
              "description" => "ABL",
              "activo" => 1,
            ],
            [
              "id" => 113,
              "dependencia_id" => 2,
              "description" => "OFICIOS",
              "activo" => 1,
            ],
            [
              "id" => 114,
              "dependencia_id" => 2,
              "description" => "SUBSIDIO POR SUBSISTENCIA",
              "activo" => 1,
            ],
            [
              "id" => 115,
              "dependencia_id" => 2,
              "description" => "SUBSIDIO POR EMPRENDIMIENTO",
              "activo" => 1,
            ],
            [
              "id" => 116,
              "dependencia_id" => 6,
              "description" => "DAI DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 117,
              "dependencia_id" => 6,
              "description" => "ADMISION DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 118,
              "dependencia_id" => 6,
              "description" => "ENTREVISTA DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 119,
              "dependencia_id" => 6,
              "description" => "RESPUESTA A DERIVACIONES DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 120,
              "dependencia_id" => 6,
              "description" => "SEGUIMIENTO DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 121,
              "dependencia_id" => 6,
              "description" => "TRATAMIENTO INDIVIDUAL DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 122,
              "dependencia_id" => 6,
              "description" => "INTERVENCION SOCIAL DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 123,
              "dependencia_id" => 6,
              "description" => "ASESORAMIENTO LEGAL DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 124,
              "dependencia_id" => 6,
              "description" => "INGRESO A HOTEL/HOGAR/REFUGIO DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 125,
              "dependencia_id" => 6,
              "description" => "GRUPO DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 126,
              "dependencia_id" => 6,
              "description" => "LICENCIA ESPECIAL DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 127,
              "dependencia_id" => 6,
              "description" => "BOTON ANTIPANICO DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 128,
              "dependencia_id" => 6,
              "description" => "ARTICULACION INTERINSTITUCIONAL",
              "activo" => 1,
            ],
            [
              "id" => 129,
              "dependencia_id" => 6,
              "description" => "RESPUESTA A OFICIO DIVERSIDAD SEXUAL",
              "activo" => 1,
            ],
            [
              "id" => 130,
              "dependencia_id" => 6,
              "description" => "DAI",
              "activo" => 1,
            ],
            [
              "id" => 131,
              "dependencia_id" => 6,
              "description" => "SEGUIMIENTO",
              "activo" => 1,
            ],
            [
              "id" => 132,
              "dependencia_id" => 6,
              "description" => "TRATAMIENTO INDIVIDUAL",
              "activo" => 1,
            ],
            [
              "id" => 133,
              "dependencia_id" => 6,
              "description" => "INTERVENCION SOCIAL",
              "activo" => 1,
            ],
            [
              "id" => 134,
              "dependencia_id" => 6,
              "description" => "INGRESO HOTEL/HOGAR/REFUGIO",
              "activo" => 1,
            ],
            [
              "id" => 135,
              "dependencia_id" => 6,
              "description" => "GRUPO",
              "activo" => 1,
            ],
            [
              "id" => 136,
              "dependencia_id" => 6,
              "description" => "ARTICULACION INTERINSTITUCIONAL",
              "activo" => 1,
            ],
            [
              "id" => 137,
              "dependencia_id" => 6,
              "description" => "RESPUESTA A OFICIO",
              "activo" => 1,
            ],
            [
              "id" => 138,
              "dependencia_id" => 6,
              "description" => "TRATAMIENTO PARA VARONES CONDUCTAS VIOLENTAS",
              "activo" => 1,
            ],
            [
              "id" => 139,
              "dependencia_id" => 6,
              "description" => "OTRAS",
              "activo" => 1,
            ],
            [
              "id" => 140,
              "dependencia_id" => 14,
              "description" => "ASESORAMIENTO GENERAL",
              "activo" => 1,
            ],
            [
              "id" => 141,
              "dependencia_id" => 3,
              "description" => "REGISTRO DE ENTIDADES NUEVAS",
              "activo" => 1,
            ],
            [
              "id" => 142,
              "dependencia_id" => 2,
              "description" => "AGENCIA NACIONAL DE DISCAPACIDAD",
              "activo" => 1,
            ],
          ];

          DB::table('tipo_tramite')->insert($data);

            /* foreach ($data as $row) {
                DB::table('tipo_tramite')->insert([
                    'id' => $row[0],
                    'dependencia_id' => $row[1],
                    'description' => $row[2],
                    'activo' => $row[3],
                ]);
            } */
    }
}
